### ISSUE TITLE
Java itests failures using java.client

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/java.client#5]
Under WSE, Gateway 5.0.1.19 is not sending CLOSE(0x30, 0x31) when the client closes the connection. It is likely that the next release of Gateway 5.0(scheduled for later today) has the fixes that were forward ported to address this issue.

To reproduce this issue, one can do the following:

0. Start Gateway 5.0.1.19
0. `git clone https://github.com/kaazing/java.client.git`
0. `cd java.client`
0. `mvn clean verify`
0. `cd ws/demo/target`
0. `java -cp . -jar gateway.client.java.demo-develop-SNAPSHOT.jar`
0. In the location field, enter `java:wse://localhost:8001/echo`
0. Press Connect button
0. Press Close button to see the exception below.

``` java
Tests run: 392, Failures: 0, Errors: 82, Skipped: 0

org.kaazing.net.ws.WebSocketException: java.lang.Exception: Connection closed abruptly
        at org.kaazing.net.ws.impl.WebSocketImpl.close(WebSocketImpl.java:261)
        at org.kaazing.net.ws.impl.WebSocketImpl.close(WebSocketImpl.java:182)
        at com.kaazing.itests.net.ws.auth.WebSocketAuthTestBase.testAuthAndText(WebSocketAuthTestBase.java:484)
        at com.kaazing.itests.net.ws.auth.WebSocketAuthTestBase.testWebSocketAuthPrimaryPort(WebSocketAuthTestBase.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
        at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)
        at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
        at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)
        at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
        at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
        at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)
        at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)
        at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)
        at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
        at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
        at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
Caused by: java.lang.Exception: Connection closed abruptly
        at org.kaazing.gateway.client.impl.wseb.DownstreamHandlerImpl.reconnectIfNecessary(DownstreamHandlerImpl.java:157)
        at org.kaazing.gateway.client.impl.wseb.DownstreamHandlerImpl.access$1200(DownstreamHandlerImpl.java:54)
        at org.kaazing.gateway.client.impl.wseb.DownstreamHandlerImpl$6.requestLoaded(DownstreamHandlerImpl.java:364)
        at org.kaazing.gateway.client.impl.http.HttpRequestTransportHandler$2.requestLoaded(HttpRequestTransportHandler.java:85)
        at org.kaazing.gateway.client.impl.http.HttpRequestDelegateHandler$1.loaded(HttpRequestDelegateHandler.java:125)
        at org.kaazing.gateway.client.transport.http.HttpRequestDelegateImpl$StreamReader.run2(HttpRequestDelegateImpl.java:326)
        at org.kaazing.gateway.client.transport.http.HttpRequestDelegateImpl$StreamReader.run(HttpRequestDelegateImpl.java:224)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by sanjay-saxena** [comment]
This cannot be reproduced with the latest Gateway 5.0 release.
