### ISSUE TITLE
WebSocketIT.echoPayloadOverWSE() fails on JDK 8

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/java.client#8]
Following exception is thrown:

``` java
org.kaazing.net.ws.WebSocketException: End of stream has reached as the connection has been closed
	at org.kaazing.net.ws.impl.io.WsMessageReaderImpl.getText(WsMessageReaderImpl.java:90)
	at org.kaazing.gateway.client.impl.ws.WebSocketIT.echoPayloadOverWSE(WebSocketIT.java:183)

```

**Comment by sanjay-saxena** [comment]
Pull request -- https://github.com/kaazing/java.client/pull/9
